[phases.setup]
nixPkgs = ["python3", "gcc"]
nixLibs = ["zlib", "stdenv.cc.cc.lib"]
aptPkgs = ["curl", "wget"]
paths = ["/opt/venv/bin"]

[phases.build]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
cacheDirectories = ["/root/.cache/pip"]

[phases.start]
cmd = ". /opt/venv/bin/activate && python app/main.py"
paths = ["/opt/venv/bin"]

[startup]
cmd = ". /opt/venv/bin/activate && python app/main.py"
