[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PORT = "30019"
ENVIRONMENT = "production"
RMBG_API_KEY = "${RMBG_API_KEY}"
PYTHON_SERVICE_HOST = "localhost"
PYTHON_SERVICE_PORT = "30020"
RAPIDAPI_PROXY_SECRET = "${RAPIDAPI_PROXY_SECRET}"
